[package]
name = "basis-universal-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3.57"
once_cell = "1.10.0"
wasm-bindgen = "0.2.80"
wasm-bindgen-futures = "0.4.30"
